language: node_js
node_js:
  - "4.1"
  - "0.12"
script:
  - npm install
  - npm run compile
  - npm run test
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
