/**
* Constants
*
* @author  Avraam Mavridis      <avr.mav@gmail.com>
*
*/

/** External Dependecies **/
import { number, string, boolean, object } from 'joi';

/** Possible options to evaluate **/
export const possibleOptions = [
  'requests',
  'gzipRequests',
  'postRequests',
  'httpsRequests',
  'notFound',
  'bodySize',
  'contentLength',
  'httpTrafficCompleted',
  'timeToFirstByte',
  'timeToLastByte',
  'ajaxRequests',
  'htmlCount',
  'htmlSize',
  'cssCount',
  'cssSize',
  'jsCount',
  'jsSize',
  'jsonCount',
  'jsonSize',
  'imageCount',
  'imageSize',
  'videoCount',
  'videoSize',
  'webfontCount',
  'webfontSize',
  'base64Count',
  'base64Size',
  'otherCount',
  'otherSize',
  'cacheHits',
  'cacheMisses',
  'cachePasses',
  'cachingNotSpecified',
  'cachingTooShort',
  'cachingDisabled',
  'oldCachingHeaders',
  'consoleMessages',
  'cookiesSent',
  'cookiesRecv',
  'domainsWithCookies',
  'documentCookiesLength',
  'documentCookiesCount',
  'documentHeight',
  'commentsSize',
  'whiteSpacesSize',
  'DOMelementsCount',
  'DOMelementMaxDepth',
  'nodesWithInlineCSS',
  'imagesScaledDown',
  'imagesWithoutDimensions',
  'DOMidDuplicated',
  'hiddenContentSize',
  'DOMmutationsInsertsv',
  'DOMmutationsRemoves',
  'DOMmutationsAttributes',
  'DOMqueries',
  'DOMqueriesWithoutResults',
  'DOMqueriesById',
  'DOMqueriesByClassName',
  'DOMqueriesByTagName',
  'DOMqueriesByQuerySelectorAll',
  'DOMinserts',
  'DOMqueriesDuplicated',
  'DOMqueriesAvoidable',
  'domains',
  'maxRequestsPerDomain',
  'medianRequestsPerDomain',
  'eventsBound',
  'eventsDispatched',
  'globalVariables',
  'globalVariablesFalsy',
  'headersCount',
  'headersSentCount',
  'headersRecvCount',
  'headersSize',
  'headersSentSize',
  'headersRecvSize',
  'headersBiggerThanContent',
  'jQueryVersion',
  'jQueryVersionsLoaded',
  'jQueryOnDOMReadyFunctions',
  'jQueryWindowOnLoadFunctions',
  'jQuerySizzleCalls',
  'jQueryEventTriggers',
  'jQueryDOMReads',
  'jQueryDOMWrites',
  'jQueryDOMWriteReadSwitches',
  'documentWriteCalls',
  'evalCalls',
  'jsErrors',
  'closedConnections',
  'localStorageEntries',
  'redirects',
  'redirectsTime',
  'repaints',
  'firstPaint',
  'requestsToDomContentLoaded',
  'requestsToDomComplete',
  'assetsNotGzipped',
  'assetsWithQueryString',
  'assetsWithCookies',
  'smallImages',
  'smallCssFiles',
  'smallJsFiles',
  'multipleRequests',
  'timeToFirstCss',
  'timeToFirstJs',
  'timeToFirstImage',
  'domInteractive',
  'domContentLoaded',
  'domContentLoadedEnd',
  'domComplete',
  'timeBackend',
  'timeFrontend',
  'statusCodesTrail',
  'windowAlerts',
  'windowConfirms',
  'windowPrompts',
  'bodyHTMLSize',
  'iframesCount',
  'smallestResponse',
  'biggestResponse',
  'fastestResponse',
  'slowestResponse',
  'smallestLatency',
  'biggestLatency',
  'medianResponse',
  'medianLatency',
];

/** performanceBudget options Schema validation **/
const _performanceBudgetSchema = {};
possibleOptions.forEach( ( val ) => _performanceBudgetSchema[ val ] = number().integer().min( 0 ) );
export const performanceBudgetSchema = _performanceBudgetSchema;

/** config options Schema validation **/
export const optionsSchema = {
  runs             : number().integer().min( 0 ),
  url              : string(),
  engine           : string(),
  timeout          : number().integer().min( 15 ),
  viewport         : string(),
  userAgent        : string(),
  noExternals      : boolean(),
  performanceBudget: object(),
};

export const defaultOptions = {
  timeout          : 60,
  runs             : 1,
  url              : 'http://www.gmail.com', // the url to be tested
  viewport         : '1280x1024',
  engine           : 'webkit', // experimental webkit, gecko
  userAgent        : 'Chrome/37.0.2062.120',
  noExternals      : false, // --no-externals block requests to 3rd party domains
  performanceBudget: {
    requests       : 2,
    medianLatency  : 10,
    slowestResponse: 1000,
  },
};
