import { number, string, boolean, object } from 'joi';

export const possibleOptions = [
  'requests',
  'gzipRequests',
  'postRequests',
  'httpsRequests',
  'notFound',
  'bodySize',
  'contentLength',
  'httpTrafficCompleted',
  'timeToFirstByte',
  'timeToLastByte',
  'ajaxRequests',
  'htmlCount',
  'htmlSize',
  'cssCount',
  'cssSize',
  'jsCount',
  'jsSize',
  'jsonCount',
  'jsonSize',
  'imageCount',
  'imageSize',
  'videoCount',
  'videoSize',
  'webfontCount',
  'webfontSize',
  'base64Count',
  'base64Size',
  'otherCount',
  'otherSize',
  'cacheHits',
  'cacheMisses',
  'cachePasses',
  'cachingNotSpecified',
  'cachingTooShort',
  'cachingDisabled',
  'oldCachingHeaders',
  'consoleMessages',
  'cookiesSent',
  'cookiesRecv',
  'domainsWithCookies',
  'documentCookiesLength',
  'documentCookiesCount',
  'documentHeight',
  'commentsSize',
  'whiteSpacesSize',
  'DOMelementsCount',
  'DOMelementMaxDepth',
  'nodesWithInlineCSS',
  'imagesScaledDown',
  'imagesWithoutDimensions',
  'DOMidDuplicated',
  'hiddenContentSize',
  'DOMmutationsInsertsv',
  'DOMmutationsRemoves',
  'DOMmutationsAttributes',
  'DOMqueries',
  'DOMqueriesWithoutResults',
  'DOMqueriesById',
  'DOMqueriesByClassName',
  'DOMqueriesByTagName',
  'DOMqueriesByQuerySelectorAll',
  'DOMinserts',
  'DOMqueriesDuplicated',
  'DOMqueriesAvoidable',
  'domains',
  'maxRequestsPerDomain',
  'medianRequestsPerDomain',
  'eventsBound',
  'eventsDispatched',
  'globalVariables',
  'globalVariablesFalsy',
  'headersCount',
  'headersSentCount',
  'headersRecvCount',
  'headersSize',
  'headersSentSize',
  'headersRecvSize',
  'headersBiggerThanContent',
  'jQueryVersion',
  'jQueryVersionsLoaded',
  'jQueryOnDOMReadyFunctions',
  'jQueryWindowOnLoadFunctions',
  'jQuerySizzleCalls',
  'jQueryEventTriggers',
  'jQueryDOMReads',
  'jQueryDOMWrites',
  'jQueryDOMWriteReadSwitches',
  'documentWriteCalls',
  'evalCalls',
  'jsErrors',
  'closedConnections',
  'localStorageEntries',
  'redirects',
  'redirectsTime',
  'repaints',
  'firstPaint',
  'requestsToDomContentLoaded',
  'requestsToDomComplete',
  'assetsNotGzipped',
  'assetsWithQueryString',
  'assetsWithCookies',
  'smallImages',
  'smallCssFiles',
  'smallJsFiles',
  'multipleRequests',
  'timeToFirstCss',
  'timeToFirstJs',
  'timeToFirstImage',
  'domInteractive',
  'domContentLoaded',
  'domContentLoadedEnd',
  'domComplete',
  'timeBackend',
  'timeFrontend',
  'statusCodesTrail',
  'windowAlerts',
  'windowConfirms',
  'windowPrompts',
  'bodyHTMLSize',
  'iframesCount',
  'smallestResponse',
  'biggestResponse',
  'fastestResponse',
  'slowestResponse',
  'smallestLatency',
  'biggestLatency',
  'medianResponse',
  'medianLatency',
];

const _performanceBudgetSchema = {};
possibleOptions.forEach( ( val ) => _performanceBudgetSchema[ val ] = number().integer().min( 0 ) );
export const performanceBudgetSchema = _performanceBudgetSchema;

export const optionsSchema = {
  runs             : number().integer().min( 0 ),
  url              : string(),
  engine           : string(),
  timeout          : number().integer().min( 15 ),
  viewport         : string(),
  userAgent        : string(),
  noExternals      : boolean(),
  performanceBudget: object(),
};
